//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hour
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string C0_from { get; set; }
        public string C0_to { get; set; }
        public string C1_from { get; set; }
        public string C1_to { get; set; }
        public string C2_from { get; set; }
        public string C2_to { get; set; }
        public string C3_from { get; set; }
        public string C3_to { get; set; }
        public string C4_from { get; set; }
        public string C4_to { get; set; }
        public string C5_from { get; set; }
        public string C5_to { get; set; }
        public string C6_from { get; set; }
        public string C6_to { get; set; }
        public decimal restorant_id { get; set; }
    
        public virtual restorant restorant { get; set; }
    }
}
