//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_has_items = new HashSet<order_has_items>();
            this.order_has_status = new HashSet<order_has_status>();
            this.ratings = new HashSet<rating>();
        }
    
        public decimal id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> address_id { get; set; }
        public decimal client_id { get; set; }
        public decimal restorant_id { get; set; }
        public Nullable<decimal> driver_id { get; set; }
        public decimal delivery_price { get; set; }
        public decimal order_price { get; set; }
        public string payment_method { get; set; }
        public string payment_status { get; set; }
        public string comment { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string srtipe_payment_id { get; set; }
        public decimal fee { get; set; }
        public decimal fee_value { get; set; }
        public decimal static_fee { get; set; }
        public int delivery_method { get; set; }
        public string delivery_pickup_interval { get; set; }
        public Nullable<decimal> vatvalue { get; set; }
        public decimal payment_processor_fee { get; set; }
        public Nullable<int> time_to_prepare { get; set; }
    
        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_has_items> order_has_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_has_status> order_has_status { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual restorant restorant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> ratings { get; set; }
    }
}
