//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string stripe_id { get; set; }
        public decimal user_id { get; set; }
        public decimal amount { get; set; }
        public string currency { get; set; }
        public string country { get; set; }
        public string provider { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
