//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_book
    {
        public int id { get; set; }
        public string phone_number { get; set; }
        public decimal resturant_id { get; set; }
    
        public virtual restorant restorant { get; set; }
    }
}
