//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public int limit_items { get; set; }
        public int limit_orders { get; set; }
        public decimal price { get; set; }
        public int period { get; set; }
        public string paddle_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string description { get; set; }
        public string features { get; set; }
        public int limit_views { get; set; }
    }
}
