//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public long id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int rating1 { get; set; }
        public string rateable_type { get; set; }
        public decimal rateable_id { get; set; }
        public decimal user_id { get; set; }
        public decimal order_id { get; set; }
        public string comment { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
    }
}
