//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restorant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public restorant()
        {
            this.categories = new HashSet<category>();
            this.hours = new HashSet<hour>();
            this.orders = new HashSet<order>();
        }
    
        public decimal id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string name { get; set; }
        public string subdomain { get; set; }
        public string logo { get; set; }
        public string cover { get; set; }
        public short active { get; set; }
        public decimal user_id { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string minimum { get; set; }
        public string description { get; set; }
        public decimal fee { get; set; }
        public decimal static_fee { get; set; }
        public string radius { get; set; }
        public short is_featured { get; set; }
        public Nullable<int> city_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hour> hours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual user user { get; set; }
    }
}
