//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string site_name { get; set; }
        public string site_logo { get; set; }
        public string search { get; set; }
        public string restorant_details_image { get; set; }
        public string restorant_details_cover_image { get; set; }
        public string description { get; set; }
        public string header_title { get; set; }
        public string header_subtitle { get; set; }
        public string currency { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string playstore { get; set; }
        public string appstore { get; set; }
        public string maps_api_key { get; set; }
        public decimal delivery { get; set; }
        public string typeform { get; set; }
        public string mobile_info_title { get; set; }
        public string mobile_info_subtitle { get; set; }
        public string order_options { get; set; }
    }
}
