//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Views.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgyptMenu.Views.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 items in the menu.
        /// </summary>
        public static string _20_items_in_the_menu {
            get {
                return ResourceManager.GetString("20 items in the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 different designs. Unlimited color options. Choose QR and Flayer style.
        /// </summary>
        public static string _8_different_designs__Unlimited_color_options__Choose_QR_and_Flayer_style {
            get {
                return ResourceManager.GetString("8 different designs. Unlimited color options. Choose QR and Flayer style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string All_rights_reserved {
            get {
                return ResourceManager.GetString("All rights reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful QR Styles.
        /// </summary>
        public static string Beautiful_QR_Styles {
            get {
                return ResourceManager.GetString("Beautiful QR Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but no menu.
        /// </summary>
        public static string but_no_menu {
            get {
                return ResourceManager.GetString("but no menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients are happy. They can see that we are a responsible Coffe and their health is a priority. No more old dirty menus :D. All they need is their phone.
        /// </summary>
        public static string Clients_are_happy__They_can_see_that_we_are_a_responsible_bar_and_their_health_is_a_priority__No_more_old_dirty_menus__D__All_they_need_is_their_phone {
            get {
                return ResourceManager.GetString("Clients are happy. They can see that we are a responsible bar and their health is" +
                        " a priority. No more old dirty menus :D. All they need is their phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community support.
        /// </summary>
        public static string Community_support {
            get {
                return ResourceManager.GetString("Community support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactless QR digital menu.
        /// </summary>
        public static string Contactless_QR_digital_menu {
            get {
                return ResourceManager.GetString("Contactless QR digital menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Digital Menu.
        /// </summary>
        public static string Create_a_Digital_Menu {
            get {
                return ResourceManager.GetString("Create a Digital Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a digital menu for your Restaurant or coffe.
        /// </summary>
        public static string Create_a_digital_menu_for_your_Restaurant_or_Bar {
            get {
                return ResourceManager.GetString("Create a digital menu for your Restaurant or Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a menu for you, now.
        /// </summary>
        public static string Create_a_menu_for_you__now_ {
            get {
                return ResourceManager.GetString("Create a menu for you, now!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR.
        /// </summary>
        public static string Create_QR {
            get {
                return ResourceManager.GetString("Create QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your menu directly on our platform. Update anytime. Easy And Simple.
        /// </summary>
        public static string Create_your_menu_directly_on_our_platform__Update_anytime__Easy_And_Simple {
            get {
                return ResourceManager.GetString("Create your menu directly on our platform. Update anytime. Easy And Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated Support.
        /// </summary>
        public static string Dedicated_Support {
            get {
                return ResourceManager.GetString("Dedicated Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design it.
        /// </summary>
        public static string Design_it {
            get {
                return ResourceManager.GetString("Design it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engage more with your customers.
        /// </summary>
        public static string Engage_more_with_your_customers {
            get {
                return ResourceManager.GetString("Engage more with your customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eur.
        /// </summary>
        public static string eur {
            get {
                return ResourceManager.GetString("eur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience it.
        /// </summary>
        public static string Experience_it {
            get {
                return ResourceManager.GetString("Experience it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras and items variants.
        /// </summary>
        public static string Extras_and_items_variants {
            get {
                return ResourceManager.GetString("Extras and items variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For bigger restaurants and bars. Offer a full menu. Limitless plan.
        /// </summary>
        public static string For_bigger_restaurants_and_bars__Offer_a_full_menu__Limitless_plan {
            get {
                return ResourceManager.GetString("For bigger restaurants and bars. Offer a full menu. Limitless plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access to QR tool.
        /// </summary>
        public static string Full_access_to_QR_tool {
            get {
                return ResourceManager.GetString("Full access to QR tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access to the menu creation tool.
        /// </summary>
        public static string Full_access_to_the_menu_creation_tool {
            get {
                return ResourceManager.GetString("Full access to the menu creation tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Digital.
        /// </summary>
        public static string Go_Digital {
            get {
                return ResourceManager.GetString("Go Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Mobile.
        /// </summary>
        public static string Go_Mobile {
            get {
                return ResourceManager.GetString("Go Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you run a small restaurant or bar, or just need the basics, this plan is great..
        /// </summary>
        public static string If_you_run_a_small_restaurant_or_bar__or_just_need_the_basics__this_plan_is_great_ {
            get {
                return ResourceManager.GetString("If you run a small restaurant or bar, or just need the basics, this plan is great" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James Curran Brooklyn Taco.
        /// </summary>
        public static string James_Curran_Brooklyn_Taco {
            get {
                return ResourceManager.GetString("James Curran Brooklyn Taco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jason Edwards Malibu Diner.
        /// </summary>
        public static string Jason_Edwards_Malibu_Diner {
            get {
                return ResourceManager.GetString("Jason Edwards Malibu Diner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jessica Evans Awang Italian Restaurant.
        /// </summary>
        public static string Jessica_Evans_Awang_Italian_Restaurant {
            get {
                return ResourceManager.GetString("Jessica Evans Awang Italian Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join now.
        /// </summary>
        public static string Join_now {
            get {
                return ResourceManager.GetString("Join now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just open the camera on your phone and scan the QR code below!.
        /// </summary>
        public static string Just_open_the_camera_on_your_phone_and_scan_the_QR_code_below_ {
            get {
                return ResourceManager.GetString("Just open the camera on your phone and scan the QR code below!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mobile app required.
        /// </summary>
        public static string No_mobile_app_required {
            get {
                return ResourceManager.GetString("No mobile app required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more printing and reprinting for some small mistake in our menu or price change. We love what QR Menu Maker have provided.
        /// </summary>
        public static string No_more_printing_and_reprinting_for_some_small_mistake_in_our_menu_or_price_change__We_love_what_QR_Menu_Maker_have_provided {
            get {
                return ResourceManager.GetString("No more printing and reprinting for some small mistake in our menu or price chang" +
                        "e. We love what QR Menu Maker have provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now your visitors will use their mobile phone camera to access your menu.
        /// </summary>
        public static string Now_your_visitors_will_use_their_mobile_phone_camera_to_access_your_menu {
            get {
                return ResourceManager.GetString("Now your visitors will use their mobile phone camera to access your menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize into categories.
        /// </summary>
        public static string Organize_into_categories {
            get {
                return ResourceManager.GetString("Organize into categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick QR color.
        /// </summary>
        public static string Pick_QR_color {
            get {
                return ResourceManager.GetString("Pick QR color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print templates for download.
        /// </summary>
        public static string Print_templates_for_download {
            get {
                return ResourceManager.GetString("Print templates for download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro yearly.
        /// </summary>
        public static string Pro_yearly {
            get {
                return ResourceManager.GetString("Pro yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Menu Maker was the perfect tool for the COVID situation. We should go earlier to this type of menu.
        /// </summary>
        public static string QR_Menu_Maker_was_the_perfect_tool_for_the_COVID_situation__We_should_go_earlier_to_this_type_of_menu {
            get {
                return ResourceManager.GetString("QR Menu Maker was the perfect tool for the COVID situation. We should go earlier " +
                        "to this type of menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time changes.
        /// </summary>
        public static string Real_time_changes {
            get {
                return ResourceManager.GetString("Real-time changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant or Coffe name.
        /// </summary>
        public static string Restaurant_or_bar_name {
            get {
                return ResourceManager.GetString("Restaurant or bar name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants and Coffe that love our QRs.
        /// </summary>
        public static string Restaurants_and_Bars_that_love_our_QRs {
            get {
                return ResourceManager.GetString("Restaurants and Bars that love our QRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richard Thomas Burger 2Go.
        /// </summary>
        public static string Richard_Thomas_Burger_2Go {
            get {
                return ResourceManager.GetString("Richard Thomas Burger 2Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as PRO, with a 20% discount. Enjoy your QR menu full year.
        /// </summary>
        public static string Same_as_PRO__with_a_20__discount__Enjoy_your_QR_menu_full_year {
            get {
                return ResourceManager.GetString("Same as PRO  with a 20% discount. Enjoy your QR menu full year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See a demo online menu.
        /// </summary>
        public static string See_a_demo_online_menu {
            get {
                return ResourceManager.GetString("See a demo online menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start free and fell in love in our pro features.
        /// </summary>
        public static string Start_free_and_fell_in_love_in_our_pro_features {
            get {
                return ResourceManager.GetString("Start free and fell in love in our pro features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with  Free.
        /// </summary>
        public static string Start_with__Free {
            get {
                return ResourceManager.GetString("Start with  Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with  Pro.
        /// </summary>
        public static string Start_with__Pro {
            get {
                return ResourceManager.GetString("Start with  Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with  Pro yearly.
        /// </summary>
        public static string Start_with__Pro_yearly {
            get {
                return ResourceManager.GetString("Start with  Pro yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superfast online menu - PWA.
        /// </summary>
        public static string Superfast_online_menu___PWA {
            get {
                return ResourceManager.GetString("Superfast online menu - PWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-align:left.
        /// </summary>
        public static string text_align {
            get {
                return ResourceManager.GetString("text align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most comprehensive platform for QR digital menu.
        /// </summary>
        public static string The_most_comprehensive_platform_for_QR_digital_menu {
            get {
                return ResourceManager.GetString("The most comprehensive platform for QR digital menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their mobile is your menu now.
        /// </summary>
        public static string Their_mobile_is_your_menu_now {
            get {
                return ResourceManager.GetString("Their mobile is your menu now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are platforms where you can create a menu but not design your QR.
        /// </summary>
        public static string There_are {
            get {
                return ResourceManager.GetString("There are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are platforms where you can make QR code.
        /// </summary>
        public static string There_are_platforms_where_you_can_make_QR_code {
            get {
                return ResourceManager.GetString("There are platforms where you can make QR code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited items in the menu.
        /// </summary>
        public static string Unlimited_items_in_the_menu {
            get {
                return ResourceManager.GetString("Unlimited items in the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited views.
        /// </summary>
        public static string Unlimited_views {
            get {
                return ResourceManager.GetString("Unlimited views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by top restaurants worldwide.
        /// </summary>
        public static string Used_by_top_restaurants_worldwide {
            get {
                return ResourceManager.GetString("Used by top restaurants worldwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View analytics.
        /// </summary>
        public static string View_analytics {
            get {
                return ResourceManager.GetString("View analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do both.
        /// </summary>
        public static string We_do_both {
            get {
                return ResourceManager.GetString("We do both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use QR Menu Maker to protect our visitors. Dirty old menus are a thing from the past. So far clients report no issues. And they love our new online menu.
        /// </summary>
        public static string We_use_QR_Menu_Maker_to_protect_our_visitors__Dirty_old_menus_are_a_thing_from_the_past__So_far_clients_report_no_issues__And_they_love_our_new_online_menu {
            get {
                return ResourceManager.GetString("We use QR Menu Maker to protect our visitors. Dirty old menus are a thing from th" +
                        "e past. So far clients report no issues. And they love our new online menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string Your_email {
            get {
                return ResourceManager.GetString("Your email", resourceCulture);
            }
        }
    }
}
