//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptMenu.Views.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgyptMenu.Views.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items in the menu.
        /// </summary>
        public static string _20_items_in_the_menu {
            get {
                return ResourceManager.GetString("20 items in the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6th of October City.
        /// </summary>
        public static string _6th_of_October_City {
            get {
                return ResourceManager.GetString("6th of October City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 different designs. Unlimited color options. Choose QR and Flayer style.
        /// </summary>
        public static string _8_different_designs__Unlimited_color_options__Choose_QR_and_Flayer_style {
            get {
                return ResourceManager.GetString("8 different designs. Unlimited color options. Choose QR and Flayer style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Few Words About Us.
        /// </summary>
        public static string A_Few_Words_About_Us {
            get {
                return ResourceManager.GetString("A Few Words About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string Add_new_category {
            get {
                return ResourceManager.GetString("Add new category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new extras.
        /// </summary>
        public static string Add_new_extras {
            get {
                return ResourceManager.GetString("Add new extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item.
        /// </summary>
        public static string Add_new_item {
            get {
                return ResourceManager.GetString("Add new item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new option.
        /// </summary>
        public static string Add_new_option {
            get {
                return ResourceManager.GetString("Add new option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plan.
        /// </summary>
        public static string Add_plan {
            get {
                return ResourceManager.GetString("Add plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Restaurant.
        /// </summary>
        public static string Add_Restaurant {
            get {
                return ResourceManager.GetString("Add Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Variant.
        /// </summary>
        public static string Add_Variant {
            get {
                return ResourceManager.GetString("Add Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Ansi office aspires by opening a branch for programming and advertising services to transfer German and European technology to the Egyptian market, through the application of the highest programming and advertising systems, with professionalism and skill commensurate with the great experience gained from working on global projects for previous companies in each of the following countries ..
        /// </summary>
        public static string Al_Ansi_office_aspires_by_opening_a_branch_for_programming_and_advertising_services_to_transfer_German_and_European_technology_to_the_Egyptian_market__through_the_application_of_the_highest_programming_and_advertising_systems__with_professionalism_and_skill_commensurate_with_the_great_experience_gained_from_working_on_global_projects_for_previous_companies_in_each_of_the_following_countries__ {
            get {
                return ResourceManager.GetString(@"Al-Ansi office aspires by opening a branch for programming and advertising services to transfer German and European technology to the Egyptian market, through the application of the highest programming and advertising systems, with professionalism and skill commensurate with the great experience gained from working on global projects for previous companies in each of the following countries .", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string All_rights_reserved {
            get {
                return ResourceManager.GetString("All rights reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this extras?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_extras_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this extras?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_item_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this item?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to items.
        /// </summary>
        public static string Back_to_items {
            get {
                return ResourceManager.GetString("Back to items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful QR Styles.
        /// </summary>
        public static string Beautiful_QR_Styles {
            get {
                return ResourceManager.GetString("Beautiful QR Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but no menu.
        /// </summary>
        public static string but_no_menu {
            get {
                return ResourceManager.GetString("but no menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name .
        /// </summary>
        public static string Category_name {
            get {
                return ResourceManager.GetString("Category name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients are happy. They can see that we are a responsible place and their health is a priority. No more old dirty menus :D. All they need is their phone.
        /// </summary>
        public static string Clients_are_happy__They_can_see_that_we_are_a_responsible_bar_and_their_health_is_a_priority__No_more_old_dirty_menus__D__All_they_need_is_their_phone {
            get {
                return ResourceManager.GetString("Clients are happy. They can see that we are a responsible bar and their health is" +
                        " a priority. No more old dirty menus :D. All they need is their phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of option values.
        /// </summary>
        public static string Comma_separated_list_of_option_values {
            get {
                return ResourceManager.GetString("Comma separated list of option values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community support.
        /// </summary>
        public static string Community_support {
            get {
                return ResourceManager.GetString("Community support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string Confirm_New_Password {
            get {
                return ResourceManager.GetString("Confirm New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactless QR digital menu.
        /// </summary>
        public static string Contactless_QR_digital_menu {
            get {
                return ResourceManager.GetString("Contactless QR digital menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Digital Menu.
        /// </summary>
        public static string Create_a_Digital_Menu {
            get {
                return ResourceManager.GetString("Create a Digital Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a digital menu for your Restaurant or cafe.
        /// </summary>
        public static string Create_a_digital_menu_for_your_Restaurant_or_Bar {
            get {
                return ResourceManager.GetString("Create a digital menu for your Restaurant or Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a menu for you  NOW.
        /// </summary>
        public static string Create_a_menu_for_you__now_ {
            get {
                return ResourceManager.GetString("Create a menu for you, now!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR.
        /// </summary>
        public static string Create_QR {
            get {
                return ResourceManager.GetString("Create QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your menu directly on our platform. Update anytime. Easy And Simple.
        /// </summary>
        public static string Create_your_menu_directly_on_our_platform__Update_anytime__Easy_And_Simple {
            get {
                return ResourceManager.GetString("Create your menu directly on our platform. Update anytime. Easy And Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Creation_Date {
            get {
                return ResourceManager.GetString("Creation Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated Support.
        /// </summary>
        public static string Dedicated_Support {
            get {
                return ResourceManager.GetString("Dedicated Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design it.
        /// </summary>
        public static string Design_it {
            get {
                return ResourceManager.GetString("Design it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t have account ?.
        /// </summary>
        public static string don_t_have_account__ {
            get {
                return ResourceManager.GetString("don\'t have account ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download JPG.
        /// </summary>
        public static string Download_JPG {
            get {
                return ResourceManager.GetString("Download JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Print Templates.
        /// </summary>
        public static string Download_Print_Templates {
            get {
                return ResourceManager.GetString("Download Print Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dropdown-menu-right.
        /// </summary>
        public static string dropdown_menu_right {
            get {
                return ResourceManager.GetString("dropdown-menu-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit extras.
        /// </summary>
        public static string Edit_extras {
            get {
                return ResourceManager.GetString("Edit extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Options.
        /// </summary>
        public static string Edit_Options {
            get {
                return ResourceManager.GetString("Edit Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Restaurant Menu.
        /// </summary>
        public static string Edit_Restaurant_Menu {
            get {
                return ResourceManager.GetString("Edit Restaurant Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGP.
        /// </summary>
        public static string EGP {
            get {
                return ResourceManager.GetString("EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        public static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable variants.
        /// </summary>
        public static string Enable_variants {
            get {
                return ResourceManager.GetString("Enable variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engage more with your customers.
        /// </summary>
        public static string Engage_more_with_your_customers {
            get {
                return ResourceManager.GetString("Engage more with your customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comma separated list of avaliable option values, ex: small,medium,large.
        /// </summary>
        public static string Enter_comma_separated_list_of_avaliable_option_values__ex__small_medium_large {
            get {
                return ResourceManager.GetString("Enter comma separated list of avaliable option values, ex: small,medium,large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a location.
        /// </summary>
        public static string Enter_location {
            get {
                return ResourceManager.GetString("Enter location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter option name, ex size.
        /// </summary>
        public static string Enter_option_name__ex_size {
            get {
                return ResourceManager.GetString("Enter option name, ex size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter variant price.
        /// </summary>
        public static string Enter_variant_price {
            get {
                return ResourceManager.GetString("Enter variant price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eur.
        /// </summary>
        public static string eur {
            get {
                return ResourceManager.GetString("eur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience it.
        /// </summary>
        public static string Experience_it {
            get {
                return ResourceManager.GetString("Experience it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras and items variants.
        /// </summary>
        public static string Extras_and_items_variants {
            get {
                return ResourceManager.GetString("Extras and items variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed-left.
        /// </summary>
        public static string fixed_dir {
            get {
                return ResourceManager.GetString("fixed dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float-right.
        /// </summary>
        public static string floating_item {
            get {
                return ResourceManager.GetString("floating item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Delivery from best restaurants.
        /// </summary>
        public static string Food_Delivery_from_best_restaurants {
            get {
                return ResourceManager.GetString("Food Delivery from best restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For bigger restaurants and bars. Offer a full menu. Limitless plan.
        /// </summary>
        public static string For_bigger_restaurants_and_bars__Offer_a_full_menu__Limitless_plan {
            get {
                return ResourceManager.GetString("For bigger restaurants and bars. Offer a full menu. Limitless plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password ?.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access to QR tool.
        /// </summary>
        public static string Full_access_to_QR_tool {
            get {
                return ResourceManager.GetString("Full access to QR tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access to the menu creation tool.
        /// </summary>
        public static string Full_access_to_the_menu_creation_tool {
            get {
                return ResourceManager.GetString("Full access to the menu creation tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamal Abd Al Nassir Axis.
        /// </summary>
        public static string Gamal_Abd_Al_Nassir_Axis {
            get {
                return ResourceManager.GetString("Gamal Abd Al Nassir Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany, France, Canada, USA, Caribbean islands, Denmark, Switzerland, Dubai.
        /// </summary>
        public static string Germany__France__Canada__USA__Caribbean_islands__Denmark__Switzerland__Dubai {
            get {
                return ResourceManager.GetString("Germany, France, Canada, USA, Caribbean islands, Denmark, Switzerland, Dubai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Digital.
        /// </summary>
        public static string Go_Digital {
            get {
                return ResourceManager.GetString("Go Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Mobile.
        /// </summary>
        public static string Go_Mobile {
            get {
                return ResourceManager.GetString("Go Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Location.
        /// </summary>
        public static string Go_to_Location {
            get {
                return ResourceManager.GetString("Go to Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you run a small restaurant or cafe , or just need the basics, this plan is great..
        /// </summary>
        public static string If_you_run_a_small_restaurant_or_bar__or_just_need_the_basics__this_plan_is_great_ {
            get {
                return ResourceManager.GetString("If you run a small restaurant or bar, or just need the basics, this plan is great" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item available.
        /// </summary>
        public static string Item_available {
            get {
                return ResourceManager.GetString("Item available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item description.
        /// </summary>
        public static string Item_description {
            get {
                return ResourceManager.GetString("Item description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Image.
        /// </summary>
        public static string Item_Image {
            get {
                return ResourceManager.GetString("Item Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item information.
        /// </summary>
        public static string Item_information {
            get {
                return ResourceManager.GetString("Item information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Management.
        /// </summary>
        public static string Item_Management {
            get {
                return ResourceManager.GetString("Item Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        public static string Item_name {
            get {
                return ResourceManager.GetString("Item name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price.
        /// </summary>
        public static string Item_Price {
            get {
                return ResourceManager.GetString("Item Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item VAT percentage.
        /// </summary>
        public static string Item_VAT_percentage {
            get {
                return ResourceManager.GetString("Item VAT percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James Curran Brooklyn Taco.
        /// </summary>
        public static string James_Curran_Brooklyn_Taco {
            get {
                return ResourceManager.GetString("James Curran Brooklyn Taco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jason Edwards Malibu Diner.
        /// </summary>
        public static string Jason_Edwards_Malibu_Diner {
            get {
                return ResourceManager.GetString("Jason Edwards Malibu Diner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jessica Evans Awang Italian Restaurant.
        /// </summary>
        public static string Jessica_Evans_Awang_Italian_Restaurant {
            get {
                return ResourceManager.GetString("Jessica Evans Awang Italian Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join now.
        /// </summary>
        public static string Join_now {
            get {
                return ResourceManager.GetString("Join now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just open the camera on your phone and scan the QR code below!.
        /// </summary>
        public static string Just_open_the_camera_on_your_phone_and_scan_the_QR_code_below_ {
            get {
                return ResourceManager.GetString("Just open the camera on your phone and scan the QR code below!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ع.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string MENU_cp {
            get {
                return ResourceManager.GetString("MENU cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Print template.
        /// </summary>
        public static string Menu_Print_template {
            get {
                return ResourceManager.GetString("Menu Print template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Theme.
        /// </summary>
        public static string Menu_Theme {
            get {
                return ResourceManager.GetString("Menu Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New option for Prosciutto crust pizza.
        /// </summary>
        public static string New_option_for_Prosciutto_crust_pizza {
            get {
                return ResourceManager.GetString("New option for Prosciutto crust pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Variant.
        /// </summary>
        public static string New_Variant {
            get {
                return ResourceManager.GetString("New Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mobile app required.
        /// </summary>
        public static string No_mobile_app_required {
            get {
                return ResourceManager.GetString("No mobile app required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more printing and reprinting for some small mistake in our menu or price change. We love what QR Menu Maker have provided.
        /// </summary>
        public static string No_more_printing_and_reprinting_for_some_small_mistake_in_our_menu_or_price_change__We_love_what_QR_Menu_Maker_have_provided {
            get {
                return ResourceManager.GetString("No more printing and reprinting for some small mistake in our menu or price chang" +
                        "e. We love what QR Menu Maker have provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string Not_Active {
            get {
                return ResourceManager.GetString("Not Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now your visitors will use their mobile phone camera to access your menu.
        /// </summary>
        public static string Now_your_visitors_will_use_their_mobile_phone_camera_to_access_your_menu {
            get {
                return ResourceManager.GetString("Now your visitors will use their mobile phone camera to access your menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of restaurants.
        /// </summary>
        public static string Number_of_restaurants {
            get {
                return ResourceManager.GetString("Number of restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders ( 30 days ).
        /// </summary>
        public static string Orders___30_days__ {
            get {
                return ResourceManager.GetString("Orders ( 30 days )", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize into categories.
        /// </summary>
        public static string Organize_into_categories {
            get {
                return ResourceManager.GetString("Organize into categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Email.
        /// </summary>
        public static string Owner_Email {
            get {
                return ResourceManager.GetString("Owner Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Email here.
        /// </summary>
        public static string Owner_Email_here {
            get {
                return ResourceManager.GetString("Owner Email here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner information.
        /// </summary>
        public static string Owner_information {
            get {
                return ResourceManager.GetString("Owner information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string Owner_Name {
            get {
                return ResourceManager.GetString("Owner Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name here.
        /// </summary>
        public static string Owner_Name_here {
            get {
                return ResourceManager.GetString("Owner Name here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Password .
        /// </summary>
        public static string Owner_Password {
            get {
                return ResourceManager.GetString("Owner Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Password here.
        /// </summary>
        public static string Owner_Password_here {
            get {
                return ResourceManager.GetString("Owner Password here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Phone.
        /// </summary>
        public static string Owner_Phone {
            get {
                return ResourceManager.GetString("Owner Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Phone here.
        /// </summary>
        public static string Owner_Phone_here {
            get {
                return ResourceManager.GetString("Owner Phone here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick QR color.
        /// </summary>
        public static string Pick_QR_color {
            get {
                return ResourceManager.GetString("Pick QR color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing plans.
        /// </summary>
        public static string Pricing_plans {
            get {
                return ResourceManager.GetString("Pricing plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print templates for download.
        /// </summary>
        public static string Print_templates_for_download {
            get {
                return ResourceManager.GetString("Print templates for download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro yearly.
        /// </summary>
        public static string Pro_yearly {
            get {
                return ResourceManager.GetString("Pro yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR builder.
        /// </summary>
        public static string QR_builder {
            get {
                return ResourceManager.GetString("QR builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Downloader.
        /// </summary>
        public static string QR_Downloader {
            get {
                return ResourceManager.GetString("QR Downloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Menu Maker.
        /// </summary>
        public static string QR_Menu_Maker {
            get {
                return ResourceManager.GetString("QR Menu Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Menu Maker was the perfect tool for the COVID situation. We should go earlier to this type of menu.
        /// </summary>
        public static string QR_Menu_Maker_was_the_perfect_tool_for_the_COVID_situation__We_should_go_earlier_to_this_type_of_menu {
            get {
                return ResourceManager.GetString("QR Menu Maker was the perfect tool for the COVID situation. We should go earlier " +
                        "to this type of menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time changes.
        /// </summary>
        public static string Real_time_changes {
            get {
                return ResourceManager.GetString("Real-time changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your restaurant.
        /// </summary>
        public static string Register_your_restaurant {
            get {
                return ResourceManager.GetString("Register your restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Cover Image.
        /// </summary>
        public static string Restaurant_Cover_Image {
            get {
                return ResourceManager.GetString("Restaurant Cover Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Description.
        /// </summary>
        public static string Restaurant_Description {
            get {
                return ResourceManager.GetString("Restaurant Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Image.
        /// </summary>
        public static string Restaurant_Image {
            get {
                return ResourceManager.GetString("Restaurant Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant information.
        /// </summary>
        public static string Restaurant_information {
            get {
                return ResourceManager.GetString("Restaurant information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Location.
        /// </summary>
        public static string Restaurant_Location {
            get {
                return ResourceManager.GetString("Restaurant Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTAURANT MANAGEMENT.
        /// </summary>
        public static string RESTAURANT_MANAGEMENT {
            get {
                return ResourceManager.GetString("RESTAURANT MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Management.
        /// </summary>
        public static string Restaurant_Management_sm {
            get {
                return ResourceManager.GetString("Restaurant Management sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Menu Management.
        /// </summary>
        public static string Restaurant_Menu_Management {
            get {
                return ResourceManager.GetString("Restaurant Menu Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Name.
        /// </summary>
        public static string Restaurant_Name {
            get {
                return ResourceManager.GetString("Restaurant Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Name here .
        /// </summary>
        public static string Restaurant_Name_here {
            get {
                return ResourceManager.GetString("Restaurant Name here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant or Cafe name.
        /// </summary>
        public static string Restaurant_or_bar_name {
            get {
                return ResourceManager.GetString("Restaurant or bar name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Restaurants {
            get {
                return ResourceManager.GetString("Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants and Cafe that love our QRs.
        /// </summary>
        public static string Restaurants_and_Bars_that_love_our_QRs {
            get {
                return ResourceManager.GetString("Restaurants and Bars that love our QRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richard Thomas Burger 2Go.
        /// </summary>
        public static string Richard_Thomas_Burger_2Go {
            get {
                return ResourceManager.GetString("Richard Thomas Burger 2Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales value.
        /// </summary>
        public static string Sales_value {
            get {
                return ResourceManager.GetString("Sales value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Volume ( 30 days ).
        /// </summary>
        public static string Sales_Volume___30_days__ {
            get {
                return ResourceManager.GetString("Sales Volume ( 30 days )", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as PRO, with a 20% discount. Enjoy your QR menu full year.
        /// </summary>
        public static string Same_as_PRO__with_a_20__discount__Enjoy_your_QR_menu_full_year {
            get {
                return ResourceManager.GetString("Same as PRO  with a 20% discount. Enjoy your QR menu full year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See a demo online menu.
        /// </summary>
        public static string See_a_demo_online_menu {
            get {
                return ResourceManager.GetString("See a demo online menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string Select_image {
            get {
                return ResourceManager.GetString("Select image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Management.
        /// </summary>
        public static string Settings_Management {
            get {
                return ResourceManager.GetString("Settings Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Description.
        /// </summary>
        public static string Site_Description {
            get {
                return ResourceManager.GetString("Site Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Info.
        /// </summary>
        public static string Site_Info {
            get {
                return ResourceManager.GetString("Site Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string Site_name {
            get {
                return ResourceManager.GetString("Site name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start free and fell in love in our pro features.
        /// </summary>
        public static string Start_free_and_fell_in_love_in_our_pro_features {
            get {
                return ResourceManager.GetString("Start free and fell in love in our pro features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with  Free.
        /// </summary>
        public static string Start_with__Free {
            get {
                return ResourceManager.GetString("Start with  Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with  Pro.
        /// </summary>
        public static string Start_with__Pro {
            get {
                return ResourceManager.GetString("Start with  Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with  Pro yearly.
        /// </summary>
        public static string Start_with__Pro_yearly {
            get {
                return ResourceManager.GetString("Start with  Pro yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superfast online menu - PWA.
        /// </summary>
        public static string Superfast_online_menu___PWA {
            get {
                return ResourceManager.GetString("Superfast online menu - PWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System status.
        /// </summary>
        public static string System_status {
            get {
                return ResourceManager.GetString("System status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team-I is an extension of the activity of Al-Ansi Office for Software development in the Federal Republic of Germany. He has been working in the Information technology area for more than 20 years, during which he worked and implemented many projects for the largest and most prestigious companies in the world..
        /// </summary>
        public static string Team_I_is_an_extension_of_the_activity_of_Al_Ansi_Office_for_Software_development_in_the_Federal_Republic_of_Germany__He_has_been_working_in_the_Information_technology_area_for_more_than_20_years__during_which_he_worked_and_implemented_many_projects_for_the_largest_and_most_prestigious_companies_in_the_world_ {
            get {
                return ResourceManager.GetString(@"Team-I is an extension of the activity of Al-Ansi Office for Software development in the Federal Republic of Germany. He has been working in the Information technology area for more than 20 years, during which he worked and implemented many projects for the largest and most prestigious companies in the world.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team i your way to the success.
        /// </summary>
        public static string Team_i_your_way_to_the_success {
            get {
                return ResourceManager.GetString("Team i your way to the success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-align:left.
        /// </summary>
        public static string text_align {
            get {
                return ResourceManager.GetString("text align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-right.
        /// </summary>
        public static string text_dir_class {
            get {
                return ResourceManager.GetString("text-dir class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comprehensive system of digital menu using the QR code through your phone&apos;s camera.
        /// </summary>
        public static string The_most_comprehensive_platform_for_QR_digital_menu {
            get {
                return ResourceManager.GetString("The most comprehensive platform for QR digital menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their mobile is your menu now.
        /// </summary>
        public static string Their_mobile_is_your_menu_now {
            get {
                return ResourceManager.GetString("Their mobile is your menu now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes demo.
        /// </summary>
        public static string Themes_demo {
            get {
                return ResourceManager.GetString("Themes demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are platforms where you can create a menu but not design your QR.
        /// </summary>
        public static string There_are {
            get {
                return ResourceManager.GetString("There are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are platforms where you can make QR code.
        /// </summary>
        public static string There_are_platforms_where_you_can_make_QR_code {
            get {
                return ResourceManager.GetString("There are platforms where you can make QR code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total orders.
        /// </summary>
        public static string Total_orders {
            get {
                return ResourceManager.GetString("Total orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited items in the menu.
        /// </summary>
        public static string Unlimited_items_in_the_menu {
            get {
                return ResourceManager.GetString("Unlimited items in the menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited views.
        /// </summary>
        public static string Unlimited_views {
            get {
                return ResourceManager.GetString("Unlimited views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by top restaurants worldwide.
        /// </summary>
        public static string Used_by_top_restaurants_worldwide {
            get {
                return ResourceManager.GetString("Used by top restaurants worldwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        public static string User_information {
            get {
                return ResourceManager.GetString("User information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants.
        /// </summary>
        public static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT percentage( calculated into item price ).
        /// </summary>
        public static string VAT_percentage {
            get {
                return ResourceManager.GetString("VAT percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View analytics.
        /// </summary>
        public static string View_analytics {
            get {
                return ResourceManager.GetString("View analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View it.
        /// </summary>
        public static string View_it {
            get {
                return ResourceManager.GetString("View it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do both.
        /// </summary>
        public static string We_do_both {
            get {
                return ResourceManager.GetString("We do both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use QR Menu Maker to protect our visitors. Dirty old menus are a thing from the past. So far clients report no issues. And they love our new online menu.
        /// </summary>
        public static string We_use_QR_Menu_Maker_to_protect_our_visitors__Dirty_old_menus_are_a_thing_from_the_past__So_far_clients_report_no_issues__And_they_love_our_new_online_menu {
            get {
                return ResourceManager.GetString("We use QR Menu Maker to protect our visitors. Dirty old menus are a thing from th" +
                        "e past. So far clients report no issues. And they love our new online menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome ! .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works from.
        /// </summary>
        public static string Works_from {
            get {
                return ResourceManager.GetString("Works from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works to.
        /// </summary>
        public static string Works_to {
            get {
                return ResourceManager.GetString("Works to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have any plans.
        /// </summary>
        public static string You_dont_have_any_plans {
            get {
                return ResourceManager.GetString("You dont have any plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Your_email {
            get {
                return ResourceManager.GetString("Your email", resourceCulture);
            }
        }
    }
}
